# Generated by Django 4.1.1 on 2022-10-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
