# Generated by Django 4.1.1 on 2022-10-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0002_alter_hero_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hp', models.IntegerField(default=100)),
                ('attack', models.IntegerField()),
                ('defence', models.IntegerField()),
            ],
        ),
    ]
