# Generated by Django 4.1.1 on 2022-10-05 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0003_monster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.hero')),
            ],
        ),
        migrations.CreateModel(
            name='MonsterInGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.game')),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.monster')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='monsters',
            field=models.ManyToManyField(through='rpg.MonsterInGame', to='rpg.monster'),
        ),
    ]
