# Generated by Django 4.1.1 on 2022-10-06 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0005_stage_next_stage_stage_previous_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='previous_stage',
        ),
    ]
